Emily/weeklydebriefbutton
cuappdev/volume-android pull request #41
Opened 2022-03-02 22:37 UTC by emilyhu8

added a button visually

2022-03-14 19:58 UTC, BenHarris4848 requested changes
Sorry for the delay on this review. One small comment but otherwise good job

2022-03-14 19:58 UTC, BenHarris4848 commented on app/build.gradle
> +    implementation "androidx.c" +
Accidental newline here

2022-03-15 04:38 UTC, dishanest approved these changes
Lookin good! A few nits here and there.

2022-03-15 04:38 UTC, dishanest commented on app/src/main/java/com/cornellappdev/volume/adapters/MorePublicationsAdapter.kt
> +    interface AdapterOnClicker{
insert newline before

2022-03-15 04:38 UTC, dishanest commented on app/src/main/java/com/cornellappdev/volume/adapters/MorePublicationsAdapter.kt
> +            mAdapterOnClicker?.onMorePublicationClicked(currentItem,isOnboarding)
add space between parameters

2022-03-15 04:38 UTC, dishanest commented on app/src/main/java/com/cornellappdev/volume/fragments/PublicationsFragment.kt
> +                                    mAdapterOnClicker = this@PublicationsFragment
indentation?

2022-03-15 04:38 UTC, dishanest commented on app/src/main/java/com/cornellappdev/volume/fragments/PublicationsFragment.kt
> +        )
Indentation. There should be an Android linter somewhere, would be good to ask @aasthashah999

2022-03-15 04:38 UTC, dishanest commented on app/src/main/res/layout/fragment_home.xml
> +
remove extra newlines in this file

2022-03-15 23:27 UTC, BenHarris4848 approved these changes
Looks good!

2022-03-15 23:27 UTC, merged